### ISSUE TITLE
[Rhetoric] broken links 

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#13]
There appear to be two links in the rhetoric keyword that return 404s: 

 * Guide to Teaching Visual Rhetoric: http://viz.cwrl.utexas.edu/node/411 at https://github.com/curateteaching/digitalpedagogy/commit/accac504e9cd27cedf002f29a0b346faa0e91db7#diff-7246768f65cd72d414672f933e269605L109
 * Assignment: Narrative Title Sequence: http://www.d.umn.edu/~cstroupe/f11/4260/narrative\_title/narrative\_title\_sequence.html at https://github.com/curateteaching/digitalpedagogy/commit/accac504e9cd27cedf002f29a0b346faa0e91db7#diff-7246768f65cd72d414672f933e269605L127

**Comment by mkgold** [comment]
The second link is fixed; hope to have an updated URL on the first soon.

**Comment by mkgold** [comment]
Hi All --

The original link for the Guide to Teaching Visual Rhetoric has disappeared. The curator is trying to get into contact with the author to see if the page might be placed in an institutional archive, but in the meantime, he supplied a link to the page on archive.org, which I think is a fine solution. We can update the link at a later date if needed. For now, please see this commit https://github.com/curateteaching/digitalpedagogy/commit/e0983acbb658838c8addd680b26d22a40e095879
