### ISSUE TITLE
[Interface] potential permission concern with Fyfe PDF

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#14]
As @kshkim noted, there may be a potential permissions concern with redistributing the Fyfe PDF at https://github.com/curateteaching/digitalpedagogy/blob/master/keywords/files/interface%20Paul-Fyfe-Not-Read.pdf, linked at https://github.com/curateteaching/digitalpedagogy/commit/3fdc66eb5a6f7ba8d9c9584f8c24e2bfebd2ae66#diff-647463ac6518b2f534dccad5c53d0a20L63. The text at the bottom of the PDF reads: 

>Copyright of Journal of Victorian Culture is the property of Routledge and its content may not be copied or emailed to multiple sites or posted to a listserv without the copyright holder's express written permission. However, users may print, download, or email articles for individual use.

I'm no expert about copyright, however, so @kshkim or @kfitz, feel free to chime in here.

**Comment by JonathanReeve** [comment]
@kfitz suggests that possibilities for fixing this include: 
 * replacing the link to the local file with a link to a file on the journal's website, if it can be found there
 * providing written proof of permission from the publisher

**Comment by triproftri** [comment]
Removed link to the copy of the article and added a link to the Taylor & Francis website. I'll ask the author/curator about further action since we have time to resolve it.
