### ISSUE TITLE
[Praxis] potential permissions concern with forthcoming artifact copy?

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#15]
As @kshkim suggested, there may be a copyright concern if a copy of "Writing on Clay" is redistributed, as is hinted at in https://github.com/curateteaching/digitalpedagogy/commit/2dedf1f8320505440c0f2aa26c8f1575e4b8cc2e#diff-49976e81dcc2ef5deee696717f129f3dR137. If this is not the case, feel free to close this issue as invalid.

**Comment by jentery** [comment]
Thanks, Jonathan. We'll touch base with Bethany et al. about it.
