### ISSUE TITLE
[Interface] MoEML Pedagogical Partners link and screenshot point to a Facebook post instead of the original project page

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#20]
In Interface.md, the link listed for "New Undergraduate Pedagogical Partnerships for Large Archival Project," https://www.facebook.com/permalink.php?story_fbid=10152947852203646&id=317355293645, links to a Facebook post instead of a page at MoEML. I assume that's not the desired target, especially since the link on the Facebook post points to a dead MoEML page that reads "MoEML has not yet added content for this page."

I'm guessing the correct page is for the MoEML Pedagogical Partnership is http://mapoflondon.uvic.ca/pedagogical_partnership.htm. 

I also noticed that the screenshot for this pedagogical partnership appears to be a screenshot of a Facebook post of a Washington College press release describing Washington College's partnership with MoEML. Perhaps the screenshot should instead be an image of the project page itself? At the very least, it could be a screenshot of the original press release, which is here: http://www.washcoll.edu/live/news/6201-washington-college-to-help-bring-renaissance. 

This issue also applies to the link as reproduced in the Works Cited section.

**Comment by triproftri** [comment]
Fixed the URL for the above artifact, but I can't replace the screenshot until Jonathan's commits are completed.

**Comment by mkgold** [comment]
Kathy, I'm thinking that we should leave this issue open until the tasks associated with it are completed, just so that we remember to do them.

**Comment by triproftri** [comment]
Ok. Good idea. I can't get my local version to sync and there isn't another
way to upload the image.

Did yall decide that using labels would work along with milestones?

**Comment by JonathanReeve** [comment]
@triproftri, all my commits for this round are in PR #19, so no need to wait for me. If you're having git troubles, I'd be happy to help, if you can describe the errors you've been getting. I could also upload the image myself, if you like.

**Comment by mkgold** [comment]
Hi Jonathan -- FYI, we are working out an internal process for dealing with pull requests. I quickly merged your first one before realizing that individual general editors really should have a chance to approve/disapprove of individual changes, since they are in many cases the equivalent of copyedits. It's a new world! Thanks for your patience.

**Comment by JonathanReeve** [comment]
Hi Matt, 
No worries. Some of my commits may be a little opinionated, and they're all lumped together into one PR, so if you find that you want to merge some but not all, I can move some of the commits to another branch. We might have a few more coming through soon, too--editorial is going to do a quick preliminary pass on it, editing directly on GitHub. (I'm so excited about that!) Some changes we may submit as another PR, and some we may keep in our fork, if they're changes that are only applicable to the web version. If you're curious about developments, they're mostly happening on the `under-review` branch of our fork. There are some neat scripts there, too, for posting to WordPress. A test site should be coming soon.

**Comment by JonathanReeve** [comment]
I should add that this quick preliminary pass through editorial (and for that matter, my commits) isn't really an editorial review, but just a few minor tweaks necessary for the markdown to convert properly through Pandoc. Chris has more about that in his forthcoming email, I believe. It's a new world, indeed!

**Comment by mkgold** [comment]
Huge thanks, Jonathan! Today's conversations have been clarifying -- I had no idea, for instance, that your team had forked the repo and were working on it actively. Many thanks for these messages and for all of your work on this.

**Comment by triproftri** [comment]
Hi Jonathan,

Ah, this notice got buried. Yes, having troubles syncing my local master of
the repository. Attached is an image of the message I get.

Also, here's the image that needs to be associated with Kathi's Interface
entry. It's title the same as the existing image. Could that be the issue?

Kathy

**Comment by JonathanReeve** [comment]
Hi Kathy, if you attached images to an email, GitHub didn't forward it to the issue. Could you drag and drop the images directly in this GitHub issue? Then I'd be happy to swap out the images and add them to my pull request. 

Also, if you post the error messages you're getting while syncing, I might be able to help.

**Comment by triproftri** [comment]
Fixed the image for the Jenstad entry so it's the original and not from a FB post.
