### ISSUE TITLE
change publication status of keywords? 

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#21]
My understanding is that editorial review will take place after peer review, and that the imminent step is "draft version undergoing peer-to-peer review." I'd recommend switching the order of these two intermediate steps, and highlighting the peer review step. If I'm in error about this, though, feel free to  close this issue.

**Comment by mkgold** [comment]
Hi Jonathan,

Thanks for this. The order is correct as is -- the four general editors do an editorial review of the keyword, and curators revise, before the keyword moves on to the peer-to-peer review stage.

We are planning to update the status of each keyword after the texts are available on the peer-to-peer review site; we will include a link to the review URL for each keyword when we do so.

Best,

Matt

**Comment by JonathanReeve** [comment]
Thanks for clearing this up for me. I was confusing MLA-side editorial discussion with the terminology on the Digital Pedagogy end.
