### ISSUE TITLE
inconsistent use of curly quotes and straight quotes

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#23]
See, for instance, the double quotation marks around the first two artifacts in the praxis keyword--the first are curly, and the second are straight.

**Comment by sarapastel** [comment]
All quotation marks should be curly.

**Comment by JonathanReeve** [comment]
Thanks, @sarapastel! I'll do a global find/replace for straight quotes on our fork.

**Comment by jentery** [comment]
Thanks, all!
