### ISSUE TITLE
inconsistent use / rendering of en-dashes and em-dashes

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#24]
This is likely partially attributable to using Pandoc markdown instead of GitHub-flavored markdown. It seems that even numbers of hyphens, like `----` (four hyphens), are converted into em-dashes, but odd numbers, like `-----` (five hyphens), are converted into an em-dash followed by a hyphen. In other places, en-dashes appear. 

Although this may be a matter better suited for Editorial, I'm logging this here since it'll be an easy matter for a global buffer find and replace operation in Vim, and provided we agree it's an issue for this phase, it's a matter I easily can fix in my next PR.

**Comment by sarapastel** [comment]
I've standardized the styling of em dashes and en dashes in Hybrid, Interface, Queer, and Rhetoric (not needed in Praxis and Video). One instance that could use a global fix is this: when dashes/hyphens appear in the place of an author's name in the list of works cited, they should be replaced with three en dashes. Also, another safe global fix is using en dashes in page ranges.

**Comment by JonathanReeve** [comment]
Thanks @sarapastel! On the technical end, I discovered what's making Pandoc convert hyphens strangely. From the Pandoc man page:  

>If the --smart option is specified, pandoc will produce typographically correct output, converting straight quotes to curly quotes, --- to em-dashes, -- to en-dashes, and ... to ellipses. Nonbreaking spaces are inserted after certain abbreviations, such as “Mr.”

Parenthetically, leaving this option on might also solve #23, if we go with straight quotes. Generally speaking, though, I think your solution of going with Unicode en and em dashes is the best idea, since it circumvents this whole issue.
