### ISSUE TITLE
[Praxis] "How did they make that?" screenshot appears to be a screenshot of a screenshot

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#25]
If you look at the screenshot for the Praxis keyword artifact "How did they make that?" (right click on the image and choose "View Image" or "Open image in new tab"), you'll see that it appears to be a screenshot of a screenshot--the page itself has a drop shadow around it, and a white border surrounds that shadow. This looks fine against a white background, and with undecorated images, but if we were to change the page background color at any point in this volume's development, or decide to apply drop shadows to the images, this particular image will start to look very strange, since it will have a drop shadow applied to the drop shadow, or it will suddenly appear to have a large white border around an inner drop shadow. Here's an exaggerated example of the double drop-shadow effect: 

![selection_487](https://cloud.githubusercontent.com/assets/1843676/6002741/0370ebdc-aac4-11e4-993a-34a36acfd959.png)

An easy solution to this would be to crop the image.

**Comment by jentery** [comment]
Image cropped!
