### ISSUE TITLE
Provide description of Advisory Board

### ISSUE THREAD

**Issue by chriszarate** [curateteaching/digitalpedagogy#26]
The description includes a list of the publication's Advisory Board:

https://github.com/curateteaching/digitalpedagogy/blob/master/description.md#advisory-board

Could you provide a sentence or two above that list that describes the role of the board in this project?

**Comment by frostdavis** [comment]
Added a description of the advisory board: https://github.com/curateteaching/digitalpedagogy/blob/master/description.md#advisory-board
