### ISSUE TITLE
Affiliations and links

### ISSUE THREAD

**Issue by briancroxall** [curateteaching/digitalpedagogy#44]
- Somehow links to Shawn Graham's site (http://electricarchaeology.ca/) aren't in the current version of the file. 
- Shawn Graham's affiliation (Carleton University) isn't in the current version.
- Ron Brooks affiliation (Oklahoma State University) isn't in the current version
- Quinn Warnick's affiliation doesn't appear after his item in the list of curated artifacts.

**Comment by mkgold** [comment]
Thanks, Brian. Are you referring to the Github site or the MLA Commons review site, or both?

**Comment by triproftri** [comment]
Brian, MLA staff has requested that these kinds of issues be included as
comments on the open peer review version. Can you add this over there
instead? -kathy

**Comment by briancroxall** [comment]
Both. I tried to do an edit on the text, but I don't have permissions to edit Master (makes sense). 

I forked the repo, but the current styling on the master is so different from what I submitted in March that I suspect that my doing a pull request wouldn't be helpful.

**Comment by briancroxall** [comment]
Sure, I can do that. Felt a bit odd leaving peer review comments on my pwn piece, so was trying this approach. I probably should have just emailed y'all.
